# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import asr_pb2 as asr__pb2

GRPC_GENERATED_VERSION = '1.67.1'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in asr_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class ASRStub(object):
    """Hauptservice für ASR-Verarbeitung (Nur Echtzeit!)
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.StreamAudio = channel.stream_stream(
                '/grpc.ASR/StreamAudio',
                request_serializer=asr__pb2.AudioChunk.SerializeToString,
                response_deserializer=asr__pb2.AudioUpdate.FromString,
                _registered_method=True)
        self.ControlASR = channel.unary_unary(
                '/grpc.ASR/ControlASR',
                request_serializer=asr__pb2.ControlRequest.SerializeToString,
                response_deserializer=asr__pb2.ControlResponse.FromString,
                _registered_method=True)


class ASRServicer(object):
    """Hauptservice für ASR-Verarbeitung (Nur Echtzeit!)
    """

    def StreamAudio(self, request_iterator, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ControlASR(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_ASRServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'StreamAudio': grpc.stream_stream_rpc_method_handler(
                    servicer.StreamAudio,
                    request_deserializer=asr__pb2.AudioChunk.FromString,
                    response_serializer=asr__pb2.AudioUpdate.SerializeToString,
            ),
            'ControlASR': grpc.unary_unary_rpc_method_handler(
                    servicer.ControlASR,
                    request_deserializer=asr__pb2.ControlRequest.FromString,
                    response_serializer=asr__pb2.ControlResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'grpc.ASR', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('grpc.ASR', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class ASR(object):
    """Hauptservice für ASR-Verarbeitung (Nur Echtzeit!)
    """

    @staticmethod
    def StreamAudio(request_iterator,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.stream_stream(
            request_iterator,
            target,
            '/grpc.ASR/StreamAudio',
            asr__pb2.AudioChunk.SerializeToString,
            asr__pb2.AudioUpdate.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ControlASR(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/grpc.ASR/ControlASR',
            asr__pb2.ControlRequest.SerializeToString,
            asr__pb2.ControlResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
